# Generated by Django 4.1.3 on 2023-01-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_rename_free_trainers_is_free_trainers_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='teches',
            new_name='teaches',
        ),
    ]
