# Generated by Django 4.1.5 on 2023-01-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Plans',
        ),
    ]
