# Generated by Django 4.1.5 on 2023-02-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_address_clients_email_clients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
