# Generated by Django 4.1.5 on 2023-02-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='age',
        ),
        migrations.AddField(
            model_name='clients',
            name='birth_date',
            field=models.DateField(default=12345),
            preserve_default=False,
        ),
    ]
